# 编排不重要的服务. 其中 jellyfin与chinesesubfinder. 可用性比较差. 且极度依赖tinymediamanager(探索次服务的替代方案)做挂削.

version: "3.4"

services:

  alist:
    image: ${alist_IMAGETAG}
    container_name: alist
    restart: always
    ports:
      - ${alist_PORT}:5244
    environment:
      - PUID=${ROOT_PUID}
      - PGID=${ROOT_PGID}
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - /etc/localtime:/etc/localtime
      - ${VOLUME}/alist:/opt/alist/data
      - ${ROOT}:/root/local
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "5244" ]
      interval: 5s
      timeout: 30s
      retries: 3

  photoprism:
    image: ${photoprism_IMAGETAG}
    container_name: photoprism
    # 测试部署OK之后再启用自动重启
    restart: always
    stop_grace_period: 10s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "${photoprism_PORT}:2342"
    environment:
      PUID: ${USUAL_PUID}
      PGID: ${USUAL_PGID}
      TZ: ${TZ}
      PHOTOPRISM_ADMIN_USER: "admin"                 # admin login username
      PHOTOPRISM_ADMIN_PASSWORD: "${photoprism_PASSWORD}"  # initial admin password (8-72 characters)
      PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_DISABLE_TLS: "true"                 # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "false"                # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "true"              # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false"            # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "${mariadb_PASSWORD}"     # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
      PHOTOPRISM_FFMPEG_ENCODER: "vaapi"             # H.264/AVC encoder (software, intel, nvidia, apple, raspberry, or vaapi)
      PHOTOPRISM_UID: ${USUAL_PUID}
      PHOTOPRISM_GID: ${USUAL_PGID}
      PHOTOPRISM_UMASK: 022
    ## Start as non-root user before initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
    user: "${USUAL_PGID}:${USUAL_PUID}"
    ## Share hardware devices with FFmpeg and TensorFlow (optional):
    devices:
      - /dev/dri:/dev/dri
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - /etc/localtime:/etc/localtime
      - ${WEBDAV}/smb/sync/sc:/photoprism/originals/sync/sc
      - ${WEBDAV}/smb/sync/sye:/photoprism/originals/sync/sye
      - ${VOLUME}/photoprism:/photoprism/storage     # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

  mariadb:
    image: ${mariadb_IMAGETAG}
    container_name: mariadb
    restart: always
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mariadbd --innodb-buffer-pool-size=1024M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    environment:
      TZ: ${TZ}
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "${mariadb_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${mariadb_PASSWORD}"
    volumes:
      - /etc/localtime:/etc/localtime
      - ${VOLUME}/mariadb:/var/lib/mysql # DO NOT REMOVE
