version: "3.4"

services:
  # 这是docker gui 用来docker的可视化操作
  portainer:
    container_name: portainer
    image: ${portainer_IMAGETAG}
    restart: always
    cap_add: [ ALL ]
    ports:
      - ${portainer_PORT}:9000
    environment:
      - /etc/localtime:/etc/localtime
      - PUID=${USUAL_PUID}
      - PGID=${USUAL_PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD", "./portainer", "--help" ]
      interval: 5s
      timeout: 30s
      retries: 3

  # 文件管理器
  filebrowser:
    container_name: filebrowser
    image: "${filebrowser_IMAGETAG}"
    restart: always
    ports:
      - ${filebrowser_PORT}:80
    environment:
      - PUID=${USUAL_PUID}
      - PGID=${USUAL_PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime
      - ${VOLUME}/filebrowser/database:/database
      - ${CONFIGS}/filebrowser:/config/filebrower
      # 这里面配置管理非系统文件的其他文件，可自行修改到/目录
      - ${ROOT}:/srv
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "80" ]
      interval: 5s
      timeout: 30s
